# Generated by Django 2.1.1 on 2019-01-24 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='車両名')),
                ('distance', models.CharField(max_length=20, verbose_name='走行距離数')),
            ],
            options={
                'verbose_name_plural': '車両',
                'verbose_name': '車両',
            },
        ),
        migrations.CreateModel(
            name='CarMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='車両名')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了日時')),
                ('content', models.CharField(max_length=20, verbose_name='メンテナンス内容')),
            ],
            options={
                'verbose_name_plural': 'メンテナンス予約',
                'verbose_name': 'メンテナンス予約',
            },
        ),
        migrations.CreateModel(
            name='CarRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='車両名')),
                ('employee_number', models.CharField(max_length=20, verbose_name='社員番号')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了日時')),
                ('start_distance', models.CharField(max_length=20, verbose_name='開始時の走行距離数')),
                ('end_distance', models.CharField(max_length=20, verbose_name='終了時の走行距離数')),
                ('destination', models.CharField(max_length=20, verbose_name='行き先')),
                ('content', models.CharField(max_length=200, verbose_name='メンテナンス内容')),
            ],
            options={
                'verbose_name_plural': '運行記録',
                'verbose_name': '運行記録',
            },
        ),
        migrations.CreateModel(
            name='CarReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='車両名')),
                ('employee_number', models.CharField(max_length=20, verbose_name='社員番号')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了日時')),
                ('destination', models.CharField(max_length=20, verbose_name='行き先')),
                ('etc_key', models.CharField(max_length=20, verbose_name='ETC利用キー')),
            ],
            options={
                'verbose_name_plural': '車両予約',
                'verbose_name': '車両予約',
            },
        ),
        migrations.CreateModel(
            name='EtcRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etc_key', models.CharField(max_length=20, verbose_name='ETCキー')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='ETC利用日')),
                ('section', models.CharField(max_length=20, verbose_name='走行区間')),
            ],
            options={
                'verbose_name_plural': 'ETC記録',
                'verbose_name': 'ETC記録',
            },
        ),
        migrations.CreateModel(
            name='RefuelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refuel_key', models.CharField(max_length=20, verbose_name='給油キー')),
                ('date', models.CharField(max_length=20, verbose_name='給油日')),
                ('location', models.CharField(max_length=20, verbose_name='給油場所')),
                ('distance', models.CharField(max_length=20, verbose_name='給油時の走行距離数')),
                ('amount', models.CharField(max_length=20, verbose_name='給油量')),
            ],
            options={
                'verbose_name_plural': '給油記録',
                'verbose_name': '給油記録',
            },
        ),
    ]
